#!/usr/bin/env bash
. ../utils/demo-magic/demo-magic.sh

# hide the evidence
clear

# Install Java on Truffle
pe '$GRAALVM_CE_HOME/bin/gu install espresso'
pe '$GRAALVM_CE_HOME/bin/gu list'

pe '$GRAALVM_CE_HOME/bin/java -truffle -version'

# Run Java on Truffle
pe 'cat HelloWorld.java'

# Start running applications
pe '$GRAALVM_CE_HOME/bin/javac HelloWorld.java'
pe '$GRAALVM_CE_HOME/bin/java -truffle HelloWorld'

pe 'cd ~/Workbench/Projects/graal-demo/spring-petclinic'
pe 'git remote -v'
pe 'mvn package -DskipTests'

pe '$GRAALVM_CE_HOME/bin/java -truffle -jar target/spring-petclinic-*.jar'
