#!/usr/bin/env bash
. ../utils/demo-magic/demo-magic.sh

# hide the evidence
clear

# Setup
pe '$GRAALVM_CE_HOME/bin/gu install native-image'
pe '$GRAALVM_CE_HOME/bin/gu list'

# Build
p 'git clone https://github.com/graalvm/simplelanguage'
cat git-clone-https-github-com-graalvm-simplelanguage.log
pe 'cd simplelanguage/'
export SL_BUILD_NATIVE=true
export JAVA_HOME=$GRAALVM_CE_HOME
pe 'mvn package -DskipTests'

# Run examples
pe 'cat language/tests/HelloWorld.sl'

read
echo '$ $GRAALVM_CE_HOME/bin/java \
    -cp launcher/target/launcher-21.2.0.jar \
    -Dtruffle.class.path.append=language/target/simplelanguage.jar \
    com.oracle.truffle.sl.launcher.SLMain language/tests/HelloWorld.sl'
read

$GRAALVM_CE_HOME/bin/java \
    -cp launcher/target/launcher-21.2.0.jar \
    -Dtruffle.class.path.append=language/target/simplelanguage.jar \
    com.oracle.truffle.sl.launcher.SLMain language/tests/HelloWorld.sl

pe 'more sl'
pe './sl language/tests/HelloWorld.sl'

pe 'cat language/tests/SumPrint.sl'
pe './sl language/tests/SumPrint.sl'

pe 'cat language/tests/Fibonacci.sl'
pe './sl language/tests/Fibonacci.sl'

# Simple Language Component for GraalVM
pe 'du -h component/sl-component.jar'
pe '$GRAALVM_CE_HOME/bin/gu -L install component/sl-component.jar'
pe '$GRAALVM_CE_HOME/bin/gu list'

# Simple Language Native Image
pe 'du -h ./native/slnative'
pe 'time ./sl language/tests/HelloWorld.sl'
pe 'time ./native/slnative language/tests/HelloWorld.sl'
